version: '2'

services:
  zabbix-db-storage:
    image: busybox:latest
    volumes:
      - /var/lib/mysql/zabbix:/var/lib/mysql
    command: sleep 10

  zabbix-db:
    image: monitoringartist/zabbix-db-mariadb
    volumes:
      - /backups:/backups
      - /etc/localtime:/etc/localtime:ro
    volumes_from:
      - zabbix-db-storage
    environment:
      - MARIADB_USER=zabbix
      - MARIADB_PASS=my_password
    networks:
      zabbix-network:
        aliases:
          - zabbix.db


  zabbix-server:
    image: monitoringartist/zabbix-3.0-xxl:latest
    ports:
      - "81:80"
      - "10051:10051"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ZS_DBHost=zabbix.db
      - ZS_DBUser=zabbix
      - ZS_DBPassword=my_password
    networks:
      zabbix-network:
        aliases:
          - zabbix-server

  zabbix-agent-xxl:
    image: monitoringartist/zabbix-agent-xxl-limited:latest
    hostname: zabbix-agent
    ports:
      - "10060:10050"
    volumes:
      - /:/rootfs
      - /var/run:/var/run
    environment:
      - ZA_Server=zabbix-server
    networks:
      zabbix-network:
        aliases:
          - zabbix-agent
networks:
  zabbix-network:
